# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.helper_images


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('cover', models.ImageField(default='default.jpg', upload_to=helpers.helper_images.make_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
